name: "Radded's Home Assistant Data Dumper"
description: "Dump time-series entity state data from Home Assistant."
# Version denotation:
# 1.2345
# | ||||_ Quickfix / hotfix
# | |||__ Minor feature
# | ||___ Major feature
# | |____ Minor release
# |______ Major release
version: 0.4643_alpha_worker_completed
slug: "radded_data_dumper"
url: https://github.com/RaddedMC/home-assistant-data-dumper
init: false
homeassistant_api: true
# TODO: Get panel for web ui working!
# ingress: true
# panel_icon: "mdi:emoticon-poop"
# panel_title: "Data Dumper"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8099/tcp: 8099
webui: "http://[HOST]:[PORT:8099]/index.html"
